export const ActionTypes = {
  UPDATE_DATA_USERS: 'UPDATE_DATA_USERS',
  UPDATE_DATA_POSTS: 'UPDATE_DATA_POSTS',
  UPDATE_DATA_ALBUMS: 'UPDATE_DATA_ALBUMS',
  UPDATE_DATA_COMMENT_POSTS: 'UPDATE_DATA_COMMENT_POSTS',
  UPDATE_DATA_DETAIL_POSTS: 'UPDATE_DATA_DETAIL_POSTS',
  UPDATE_DATA_PHOTOS: 'UPDATE_DATA_PHOTOS',
  UPDATE_DATA_DETAIL_PHOTOS: 'UPDATE_DATA_DETAIL_PHOTOS',
};

export default ActionTypes;
